update Sphinx workflow

diff --git a/.github/workflows/doc_pages.yml b/.github/workflows/doc_pages.yml
--- a/.github/workflows/doc_pages.yml
+++ b/.github/workflows/doc_pages.yml
@@ -3,11 +3,13 @@ name: Deploy Sphinx Documentation to GitHub Pages
 on:
   push:
     branches:
-      - main  # Adjust this to your default branch
+      - update_documentation
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
     steps:
       - name: Check out the repository
         uses: actions/checkout@v3
@@ -15,17 +17,36 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.9'
+          python-version: '3.11'
+
+      - name: Cache Python dependencies
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/doc/requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
 
       - name: Install dependencies
-        run: pip install sphinx sphinx-rtd-theme
+        run: pip install -r requirements.txt
+        working-directory: doc
 
       - name: Build documentation
         run: make html
-        working-directory: docs  # Adjust to your Sphinx docs directory
+        working-directory: doc          
+
+      - name: Test Documentation Build
+        run: |
+          if [ ! -d "doc/_build/html" ]; then
+            echo "Build failed: HTML directory not found."
+            exit 1
+          fi
+        working-directory: doc
 
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
+          publish_branch: gh-pages
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: docs/_build/html
+          publish_dir: doc/_build/html
+          force_orphan: true
